<?php

use Illuminate\Database\Seeder;

class KeywordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [   
            ['keywordID'=>'K0001','categoryID'=>'C0001','keywordName'=>'family'],
            ['keywordID'=>'K0002','categoryID'=>'C0001','keywordName'=>'parent'],
            ['keywordID'=>'K0003','categoryID'=>'C0001','keywordName'=>'parents'],
            ['keywordID'=>'K0004','categoryID'=>'C0001','keywordName'=>'kin'],
            ['keywordID'=>'K0005','categoryID'=>'C0001','keywordName'=>'kinship'],
            ['keywordID'=>'K0006','categoryID'=>'C0001','keywordName'=>'mother'],
            ['keywordID'=>'K0007','categoryID'=>'C0001','keywordName'=>'mama'],
            ['keywordID'=>'K0008','categoryID'=>'C0001','keywordName'=>'father'],
            ['keywordID'=>'K0009','categoryID'=>'C0001','keywordName'=>'papa'],
            ['keywordID'=>'K0010','categoryID'=>'C0001','keywordName'=>'brother'],
            ['keywordID'=>'K0011','categoryID'=>'C0001','keywordName'=>'bro'],
            ['keywordID'=>'K0012','categoryID'=>'C0001','keywordName'=>'sister'],
            ['keywordID'=>'K0013','categoryID'=>'C0001','keywordName'=>'sis'],
            ['keywordID'=>'K0014','categoryID'=>'C0001','keywordName'=>'sibling'],
            ['keywordID'=>'K0015','categoryID'=>'C0001','keywordName'=>'siblings'],
            ['keywordID'=>'K0016','categoryID'=>'C0001','keywordName'=>'sibs'],
            ['keywordID'=>'K0017','categoryID'=>'C0001','keywordName'=>'grandfather'],
            ['keywordID'=>'K0018','categoryID'=>'C0001','keywordName'=>'grandad'],
            ['keywordID'=>'K0019','categoryID'=>'C0001','keywordName'=>'grandpa'],
            ['keywordID'=>'K0020','categoryID'=>'C0001','keywordName'=>'grandmother'],
            ['keywordID'=>'K0021','categoryID'=>'C0001','keywordName'=>'grandma'],
            ['keywordID'=>'K0022','categoryID'=>'C0001','keywordName'=>'mum'],
            ['keywordID'=>'K0023','categoryID'=>'C0001','keywordName'=>'child support'],

            ['keywordID'=>'K0024','categoryID'=>'C0002','keywordName'=>'sorry'],
            ['keywordID'=>'K0025','categoryID'=>'C0002','keywordName'=>'tragic'],
            ['keywordID'=>'K0026','categoryID'=>'C0002','keywordName'=>'lamentable'],
            ['keywordID'=>'K0027','categoryID'=>'C0002','keywordName'=>'lament'],
            ['keywordID'=>'K0028','categoryID'=>'C0002','keywordName'=>'pitiful'],
            ['keywordID'=>'K0029','categoryID'=>'C0002','keywordName'=>'mournful'],
            ['keywordID'=>'K0030','categoryID'=>'C0002','keywordName'=>'bad'],
            ['keywordID'=>'K0031','categoryID'=>'C0002','keywordName'=>'bittersweet'],
            ['keywordID'=>'K0032','categoryID'=>'C0002','keywordName'=>'sorrow'],
            ['keywordID'=>'K0033','categoryID'=>'C0002','keywordName'=>'sorrrowful'],
            ['keywordID'=>'K0034','categoryID'=>'C0002','keywordName'=>'miserable'],
            ['keywordID'=>'K0035','categoryID'=>'C0002','keywordName'=>'unhappy'],
            ['keywordID'=>'K0036','categoryID'=>'C0002','keywordName'=>'depressing'],
            ['keywordID'=>'K0037','categoryID'=>'C0002','keywordName'=>'depressed'],
            ['keywordID'=>'K0038','categoryID'=>'C0002','keywordName'=>'lone'],
            ['keywordID'=>'K0039','categoryID'=>'C0002','keywordName'=>'lonely'],
            ['keywordID'=>'K0040','categoryID'=>'C0002','keywordName'=>'alone'],
            ['keywordID'=>'K0041','categoryID'=>'C0002','keywordName'=>'pity'],
            ['keywordID'=>'K0042','categoryID'=>'C0002','keywordName'=>'heavyhearted'],
            ['keywordID'=>'K0043','categoryID'=>'C0002','keywordName'=>'heavyheart'],
            ['keywordID'=>'K0044','categoryID'=>'C0002','keywordName'=>'brokenhearted'],
            ['keywordID'=>'K0045','categoryID'=>'C0002','keywordName'=>'heartbroken'],
            ['keywordID'=>'K0046','categoryID'=>'C0002','keywordName'=>'tragical'],
            ['keywordID'=>'K0047','categoryID'=>'C0002','keywordName'=>'awful'],
            ['keywordID'=>'K0048','categoryID'=>'C0002','keywordName'=>'sad'],
            ['keywordID'=>'K0049','categoryID'=>'C0002','keywordName'=>'sadness'],
            ['keywordID'=>'K0050','categoryID'=>'C0002','keywordName'=>'regret'],
            ['keywordID'=>'K0051','categoryID'=>'C0002','keywordName'=>'terrible'],
            ['keywordID'=>'K0052','categoryID'=>'C0002','keywordName'=>'hopeless'],
            ['keywordID'=>'K0053','categoryID'=>'C0002','keywordName'=>'gloomy'],
            ['keywordID'=>'K0054','categoryID'=>'C0002','keywordName'=>'gloom'],
            ['keywordID'=>'K0055','categoryID'=>'C0002','keywordName'=>'unlucky'],
            ['keywordID'=>'K0056','categoryID'=>'C0002','keywordName'=>'crying'],
            ['keywordID'=>'K0057','categoryID'=>'C0002','keywordName'=>'rejection'],
            ['keywordID'=>'K0058','categoryID'=>'C0002','keywordName'=>'grieve'],
            ['keywordID'=>'K0059','categoryID'=>'C0002','keywordName'=>'saddening'],
            ['keywordID'=>'K0060','categoryID'=>'C0002','keywordName'=>'worse'],
            ['keywordID'=>'K0061','categoryID'=>'C0002','keywordName'=>'feeling down'],

            ['keywordID'=>'K0062','categoryID'=>'C0003','keywordName'=>'sacred'],
            ['keywordID'=>'K0063','categoryID'=>'C0003','keywordName'=>'inspirational'],
            ['keywordID'=>'K0064','categoryID'=>'C0003','keywordName'=>'inspiration'],
            ['keywordID'=>'K0065','categoryID'=>'C0003','keywordName'=>'inspire'],
            ['keywordID'=>'K0066','categoryID'=>'C0003','keywordName'=>'lively'],
            ['keywordID'=>'K0067','categoryID'=>'C0003','keywordName'=>'imaginative'],
            ['keywordID'=>'K0068','categoryID'=>'C0003','keywordName'=>'poetic'],
            ['keywordID'=>'K0069','categoryID'=>'C0003','keywordName'=>'eloquent'],
            ['keywordID'=>'K0070','categoryID'=>'C0003','keywordName'=>'passionate'],
            ['keywordID'=>'K0071','categoryID'=>'C0003','keywordName'=>'insightful'],
            ['keywordID'=>'K0072','categoryID'=>'C0003','keywordName'=>'entertaining'],
            ['keywordID'=>'K0073','categoryID'=>'C0003','keywordName'=>'brilliant'],
            ['keywordID'=>'K0074','categoryID'=>'C0003','keywordName'=>'memorable'],
            ['keywordID'=>'K0075','categoryID'=>'C0003','keywordName'=>'humorous'],
            ['keywordID'=>'K0076','categoryID'=>'C0003','keywordName'=>'uplifting'],
            ['keywordID'=>'K0077','categoryID'=>'C0003','keywordName'=>'captivating'],
            ['keywordID'=>'K0078','categoryID'=>'C0003','keywordName'=>'terrific'],
            ['keywordID'=>'K0079','categoryID'=>'C0003','keywordName'=>'impassioned'],
            ['keywordID'=>'K0080','categoryID'=>'C0003','keywordName'=>'wonderful'],
            ['keywordID'=>'K0081','categoryID'=>'C0003','keywordName'=>'timeless'],
            ['keywordID'=>'K0082','categoryID'=>'C0003','keywordName'=>'delightful'],
            ['keywordID'=>'K0083','categoryID'=>'C0003','keywordName'=>'heartfelt'],
            ['keywordID'=>'K0084','categoryID'=>'C0003','keywordName'=>'mesmerizing'],

            ['keywordID'=>'K0085','categoryID'=>'C0004','keywordName'=>'happy'],
            ['keywordID'=>'K0086','categoryID'=>'C0004','keywordName'=>'glad'],
            ['keywordID'=>'K0087','categoryID'=>'C0004','keywordName'=>'positive'],
            ['keywordID'=>'K0088','categoryID'=>'C0004','keywordName'=>'fortunate'],
            ['keywordID'=>'K0089','categoryID'=>'C0004','keywordName'=>'delightful'],
            ['keywordID'=>'K0090','categoryID'=>'C0004','keywordName'=>'heartfelt'],
            ['keywordID'=>'K0091','categoryID'=>'C0004','keywordName'=>'wonderful'],
            ['keywordID'=>'K0092','categoryID'=>'C0004','keywordName'=>'terrific'],
            ['keywordID'=>'K0093','categoryID'=>'C0004','keywordName'=>'entertaining'],
            ['keywordID'=>'K0094','categoryID'=>'C0004','keywordName'=>'humorous'],
            ['keywordID'=>'K0095','categoryID'=>'C0004','keywordName'=>'entertaining'],
            ['keywordID'=>'K0096','categoryID'=>'C0004','keywordName'=>'brilliant'],
            ['keywordID'=>'K0097','categoryID'=>'C0004','keywordName'=>'laughter'],
            ['keywordID'=>'K0098','categoryID'=>'C0004','keywordName'=>'cheerful'],
            ['keywordID'=>'K0099','categoryID'=>'C0004','keywordName'=>'prosperous'],
            ['keywordID'=>'K0100','categoryID'=>'C0004','keywordName'=>'blessed'],
            ['keywordID'=>'K0101','categoryID'=>'C0004','keywordName'=>'prosper'],
            ['keywordID'=>'K0102','categoryID'=>'C0004','keywordName'=>'good'],
            ['keywordID'=>'K0103','categoryID'=>'C0004','keywordName'=>'positive'],
            ['keywordID'=>'K0104','categoryID'=>'C0004','keywordName'=>'wonderful'],
            ['keywordID'=>'K0105','categoryID'=>'C0004','keywordName'=>'joyous'],
            ['keywordID'=>'K0106','categoryID'=>'C0004','keywordName'=>'joyful'],
            ['keywordID'=>'K0107','categoryID'=>'C0004','keywordName'=>'joy'],

            ['keywordID'=>'K0108','categoryID'=>'C0005','keywordName'=>'success'],
            ['keywordID'=>'K0109','categoryID'=>'C0005','keywordName'=>'successful'],
            ['keywordID'=>'K0110','categoryID'=>'C0005','keywordName'=>'conquest'],
            ['keywordID'=>'K0111','categoryID'=>'C0005','keywordName'=>'achieved'],
            ['keywordID'=>'K0112','categoryID'=>'C0005','keywordName'=>'triumph'],
            ['keywordID'=>'K0113','categoryID'=>'C0005','keywordName'=>'victory'],
            ['keywordID'=>'K0114','categoryID'=>'C0005','keywordName'=>'great'],
            ['keywordID'=>'K0115','categoryID'=>'C0005','keywordName'=>'winning'],
            ['keywordID'=>'K0116','categoryID'=>'C0005','keywordName'=>'breakthrough'],
            ['keywordID'=>'K0117','categoryID'=>'C0005','keywordName'=>'experience'],
            ['keywordID'=>'K0118','categoryID'=>'C0005','keywordName'=>'progress'],
            ['keywordID'=>'K0119','categoryID'=>'C0005','keywordName'=>'achievement'],
            ['keywordID'=>'K0120','categoryID'=>'C0005','keywordName'=>'hardwork'],
            ['keywordID'=>'K0121','categoryID'=>'C0005','keywordName'=>'perseverance'],
            
        ];

        DB::table('keywords')->insert($data);
    }
}
